document.writeln('<script src="browserdetect.js"></script>')
document.writeln('<script src="keys.js"></script>')
document.writeln('<script src="util.js"></script>')
document.writeln('<script src="mouse.js"></script>')
document.writeln('<script src="sound.js"></script>')
document.writeln('<script src="entity.js"></script>')
document.writeln('<script src="template.js"></script>')
document.writeln('<script src="missile.js"></script>')
document.writeln('<script src="avatar.js"></script>')
document.writeln('<script src="player.js"></script>')
document.writeln('<script src="agent.js"></script>')
document.writeln('<script src="exit.js"></script>')
document.writeln('<script src="main.js"></script>')

